#!/usr/bin/env python3
"""
Bundle — packages the 12-tool toolkit for delivery to a buyer.
Creates toolkit.zip containing every tool, the README, the demo site,
and a GETTING-STARTED.txt, then prints the sha256 so the gig delivery
message can state the exact artifact fingerprint.
"""

import hashlib
import zipfile
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "toolkit.zip"

INCLUDE = [
    # tools
    "scrapekit.py", "fileforge.py", "promptflow.py", "leadminer.py",
    "apiforge.py", "reportforge.py", "csvkit.py", "mediasift.py",
    "sitedoctor.py", "faqforge.py", "mailforge.py", "taskloop.py",
    # docs
    "README.md",
    # demo site (all files, recursively)
    "demos/",
]
EXCLUDE_DIRS = {"__pycache__"}
EXCLUDE_FILES = {"demosite.py", "bundle.py", "toolkit.zip"}

GETTING_STARTED = """\
THE 12-TOOL AUTOMATION TOOLKIT
=============================
Requirements: Python 3.9 or newer. Nothing to install — every tool uses
only the standard library.

START HERE: README.md documents every tool, with examples, market usage,
and the full test log.

QUICK TEST (60 seconds):
    python scrapekit.py https://example.com --links
    python fileforge.py report . --format csv --out my-inventory.csv
    python promptflow.py list

The demos/ folder contains a catalog page (open demos/index.html in any
browser) with live sample deliverables generated by the tools themselves.

Every mutating tool is dry-run by default: pass --apply only when you
mean it. Nothing phones home; scrapers are rate-limited and respect
robots.txt.
"""


def iter_files(base: Path):
    if base.is_file():
        yield base
        return
    for path in base.rglob("*"):
        if path.is_file() and path.name not in EXCLUDE_FILES \
                and not any(part in EXCLUDE_DIRS for part in path.parts):
            yield path


def main():
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as zf:
        for entry in INCLUDE:
            for path in iter_files(ROOT / entry):
                zf.write(path, path.relative_to(ROOT))
        zf.writestr("GETTING-STARTED.txt", GETTING_STARTED)

    size = OUT.stat().st_size
    digest = hashlib.sha256(OUT.read_bytes()).hexdigest()
    print(f"bundled: {OUT.name} ({size / 1024:.0f} KB, "
          f"{len(zipfile.ZipFile(OUT).namelist())} files)")
    print(f"sha256:  {digest}")
    print("delivery: send this zip + the README section for the ordered tool")


if __name__ == "__main__":
    main()
